### ISSUE TITLE
More explanation on OGB reproducibility

### ISSUE THREAD

**Issue by weihua916** [toenshoff/CRaWl#3]
Thank you for the leaderboard submission. In your README.md, Could you please provide a more detailed step-by-step tutorial of how to reproduce your molpcba result?

**Comment by toenshoff** [comment]
Sure, I have just updated the readme. Note that the newest versions of the involved packages should also work, but the original results were obtained with the specified versions. So for reproducibility it is probably best to use the exact same versions.

**Comment by weihua916** [comment]
Great, thanks! updated the leaderbaord.
